[alembic]
script_location = migrations
# sqlalchemy.url = postgresql+asyncpg://postgres:postgres@localhost:5432/reals
sqlalchemy.url = postgresql://reals_db_user:Y377mgYEM7UGnKv4j3niTceukgHhKikp@dpg-cultt1lumphs7389ogq0-a.oregon-postgres.render.com/reals_db

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S 