"""update test db

Revision ID: 07ecc73e3c8f
Revises: 1152a767e235
Create Date: 2025-02-15 01:10:12.941648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ecc73e3c8f'
down_revision: Union[str, None] = '1152a767e235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'is_valid_response',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'is_valid_response',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ### 