"""set response fieldas false

Revision ID: 1152a767e235
Revises: ce6bc0416047
Create Date: 2025-02-13 22:40:43.248934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1152a767e235"
down_revision: Union[str, None] = "ce6bc0416047"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
        UPDATE sessions 
        SET is_valid_response = false 
        WHERE is_valid_response IS NULL OR is_valid_response = true
    """
    )
    op.alter_column(
        "sessions",
        "is_valid_response",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "is_valid_response",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )

    # op.drop_column('sessions', 'is_valid_response')
    # ### end Alembic commands ###
