"""Update Api Request log

Revision ID: 17b3ddc74aa0
Revises: 24a739b036eb
Create Date: 2025-02-11 00:18:06.469585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17b3ddc74aa0'
down_revision: Union[str, None] = '24a739b036eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_request_logs', sa.Column('log', sa.String(length=9999), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_request_logs', 'log')
    # ### end Alembic commands ### 