"""Update Api Request log

Revision ID: 519c8a84bddf
Revises: c5ec1b44f34b
Create Date: 2025-02-11 01:17:14.781920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519c8a84bddf'
down_revision: Union[str, None] = 'c5ec1b44f34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 