"""sync_schema

Revision ID: 612dd8a6833a
Revises: 71a5608921c1
Create Date: 2025-02-08 03:15:53.672838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '612dd8a6833a'
down_revision: Union[str, None] = '71a5608921c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_usage', sa.Column('session_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'api_usage', 'sessions', ['session_id'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('messages_session_uuid_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'sessions', ['session_uuid'], ['uuid'], ondelete='CASCADE')
    op.drop_constraint('sessions_user_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['uuid'], ondelete='CASCADE')
    op.drop_column('sessions', 'last_accessed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_accessed', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_user_id_fkey', 'sessions', 'users', ['user_id'], ['uuid'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_session_uuid_fkey', 'messages', 'sessions', ['session_uuid'], ['uuid'])
    op.drop_constraint(None, 'api_usage', type_='foreignkey')
    op.drop_column('api_usage', 'session_id')
    # ### end Alembic commands ### 