"""change all is_active to true

Revision ID: a3a21bc3fba2
Revises: ac0cfb64a249
Create Date: 2025-02-13 22:13:30.618467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3a21bc3fba2"
down_revision: Union[str, None] = "ac0cfb64a249"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE sessions
        SET is_active = true 
        WHERE is_active IS NULL OR is_active = false
    """
    )

    # Make is_active column NOT NULL with default true
    op.alter_column(
        "sessions",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        server_default=sa.text("true"),
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "is_active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        server_default=None,
    )
    pass
    # ### end Alembic commands ###
