"""add active field on session

Revision ID: ac0cfb64a249
Revises: 001cdc02dfb7
Create Date: 2025-02-13 22:10:24.508743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac0cfb64a249'
down_revision: Union[str, None] = '001cdc02dfb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'is_active')
    # ### end Alembic commands ### 