"""Update Api Request log

Revision ID: c5ec1b44f34b
Revises: 975acc080aa8
Create Date: 2025-02-11 01:03:45.106062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5ec1b44f34b'
down_revision: Union[str, None] = '975acc080aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_usage', 'rate_limit_reset')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_usage', sa.Column('rate_limit_reset', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 