"""add valid response field

Revision ID: ce6bc0416047
Revises: a3a21bc3fba2
Create Date: 2025-02-13 22:35:09.049129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ce6bc0416047"
down_revision: Union[str, None] = "a3a21bc3fba2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        """
        UPDATE session 
        SET is_valid_response = true 
        WHERE is_valid_response IS NULL OR is_valid_response = false
    """
    )
    op.alter_column(
        "session",
        "is_valid_response",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session",
        "is_valid_response",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("true"),
    )

    # op.drop_column('sessions', 'is_valid_response')
    # ### end Alembic commands ###
